baseURL = 'https://lyra.horse/blog/'
languageCode = 'en-us'
title = "lyra's epic blog"
theme = 'minty'
disableHugoGeneratorInject = false
capitalizeListTitles = false
pluralizeListTitles = false

[permalinks]
  [permalinks.page]
  	posts = '/:year/:month/:slug/'

[markup.goldmark.renderer]
  unsafe = true