baseURL = 'https://lyra.horse/blog/'
languageCode = 'en-us'
title = "lyra's epic blog"
theme = 'minty'
disableHugoGeneratorInject = false
capitalizeListTitles = false
pluralizeListTitles = false

[security]
  enableInlineShortcodes = true

[services.rss]
  limit = 1000

[permalinks]
  [permalinks.page]
  	posts = '/:year/:month/:slug/'

[markup.goldmark.Extensions]
  footnote = true
[markup.goldmark.renderer]
  unsafe = true